def summarize_categorical_column(column):
    print("Column: %s" % column.name)
    missingPct = (column.isnull().sum() / len(column)) * 100
    print("column type: %s" % column.dtype)
    print("%f%% missing values" % missingPct)
    print("%d unique values" % column.unique().size)
    print(column.value_counts())

def summarize_ordinal_column(column):
    print("Column: %s" % column.name)
    num_missing = column.isnull().sum()
    missing_pct = (num_missing / len(column)) * 100
    print("column type: %s" % column.dtype)
    print("%d missing values" % num_missing)
    print("%f%% missing values" % missing_pct)
    print("maximum value: %s" % column.max())
    print("maximum value: %s" % column.min())

def clean_countries(country_column):
    """
    given a pd column with countries, combine countrires and their territories
    """
    print("%d unique values before replacements" % country_column.unique().size)
    country_column.replace('PALESTINE BORN BEFORE 1948', 'PALESTINE', inplace=True)
    country_column.replace('Palestine', 'PALESTINE', inplace=True)
    country_column.replace('CHINA, PEOPLES REPUBLIC OF', 'CHINA', inplace=True)
    country_column.replace('HONG KONG', 'CHINA', inplace=True)
    country_column.replace('MACAU', 'CHINA', inplace=True)
    country_column.replace('BRITISH VIRGIN ISLANDS', 'UNITED KINGDOM', inplace=True)
    country_column.replace('BERMUDA', 'UNITED KINGDOM', inplace=True)
    country_column.replace('NETHERLANDS ANTILLES', 'NETHERLANDS', inplace=True)
    country_column.replace('SAINT MARTIN(FRENCH)', 'FRANCE', inplace=True)
    country_column.replace('FRENCH POLYNESIA', 'FRANCE', inplace=True)
    country_column.replace('GUADELOUPE', 'FRANCE', inplace=True)
    country_column.replace('SAINT BARTHELEMY', 'FRANCE', inplace=True)
    country_column.replace('NEW CALEDONIA', 'FRANCE', inplace=True)
    country_column.replace('REUNION', 'FRANCE', inplace=True)
    country_column.replace('FRENCH GUIANA', 'FRANCE', inplace=True)
    country_column.replace('SINT MAARTEN(DUTCH)', 'NETHERLANDS', inplace=True)
    country_column.replace('ARUBA', 'NETHERLANDS', inplace=True)
    country_column.replace('SINT EUSTATIUS', 'NETHERLANDS', inplace=True)
    country_column.replace('SABA', 'NETHERLANDS', inplace=True)
    country_column.replace('BONAIRE', 'NETHERLANDS', inplace=True)
    country_column.replace('CURACAO', 'NETHERLANDS', inplace=True)
    country_column.replace('TURKS AND CAICOS ISLANDS', 'UNITED KINGDOM', inplace=True)
    country_column.replace('CAYMAN ISLANDS', 'UNITED KINGDOM', inplace=True)
    country_column.replace('MONTSERRAT', 'UNITED KINGDOM', inplace=True)
    country_column.replace('ANGUILLA', 'UNITED KINGDOM', inplace=True)
    country_column.replace('ST. HELENA', 'UNITED KINGDOM', inplace=True)
    country_column.replace('CHRISTMAS ISLAND', 'AUSTRALIA', inplace=True)
    country_column.replace('COCOS ISLANDS', 'AUSTRALIA', inplace=True)
    country_column.replace('FALKLAND ISLANDS', 'UNITED KINGDOM', inplace=True)
    country_column.replace('FRENCH SOUTHERN AND ANTARCTIC', 'FRANCE', inplace=True)
    country_column.replace('GIBRALTAR', 'UNITED KINGDOM', inplace=True)
    country_column.replace('MARTINIQUE', 'FRANCE', inplace=True)
    country_column.replace('GUAM', 'UNITED STATES', inplace=True)
    print("%d unique values after replacements" % country_column.unique().size)
    print("replacing %d null values with 'UNKNOWN'" % country_column.isnull().sum())
    country_column.fillna('UNKNOWN', inplace=True)