from tables import Tables
from enum import Enum, auto

class Columns(Enum):
    # encounters
    EVENT_DATE = ("Event Date", Tables.ENCOUNTERS, "", False, False)
    RESPONSIBLE_AOR = ("Responsible AOR", Tables.ENCOUNTERS, "", False, False)
    RESPONSIBLE_SITE = ("Responsible Site", Tables.ENCOUNTERS, "", False, False)
    LEAD_EVENT_TYPE = ("Lead Event Type", Tables.ENCOUNTERS, "", False, False)
    LEAD_SOURCE = ("Lead Source", Tables.ENCOUNTERS, "", False, False)
    EVENT_TYPE = ("Event Type", Tables.ENCOUNTERS, "", False, False)
    FINAL_PROGRAM = ("Final Program", Tables.ENCOUNTERS, "", False, False)
    FINAL_PROGRAM_GROUP = ("Final Program Group", Tables.ENCOUNTERS, "", True, False)
    ENCOUNTER_CRIMINALITY = ("Encounter Criminality", Tables.ENCOUNTERS, "", False, False)
    PROCESSING_DISPOSITION = ("Processing Disposition", Tables.ENCOUNTERS, "", False, False)
    CASE_STATUS = ("Case Status", Tables.ENCOUNTERS, "", False, False)
    CASE_CATEGORY = ("Case Category", Tables.ENCOUNTERS, "", False, False)
    DEPARTED_DATE = ("Departed Date", Tables.ENCOUNTERS, "", False, False)
    DEPARTURE_COUNTRY = ("Departure Country", Tables.ENCOUNTERS, "", False, False)
    FINAL_ORDER_YES_NO = ("Final Order Yes No", Tables.ENCOUNTERS, "", False, False)
    FINAL_ORDER_DATE = ("Final Order Date", Tables.ENCOUNTERS, "", False, False)
    BIRTH_DATE = ("Birth Date", Tables.ENCOUNTERS, "", True, False)
    BIRTH_YEAR = ("Birth Year", Tables.ENCOUNTERS, "", False, False)
    CITIZENSHIP_COUNTRY = ("Citizenship Country", Tables.ENCOUNTERS, "", False, False)
    GENDER = ("Gender", Tables.ENCOUNTERS, "", False, False)
    EVENT_LANDMARK = ("Event Landmark", Tables.ENCOUNTERS, "", False, False)
    ALIEN_FILE_NUMBER = ("Alien File Number", Tables.ENCOUNTERS, "", True, False)
    EID_CASE_ID = ("EID Case ID", Tables.ENCOUNTERS, "", True, False)
    EID_SUBJECT_ID = ("EID Subject ID", Tables.ENCOUNTERS, "", True, False)
    UNIQUE_IDENTIFIER = ("Unique Identifier", Tables.ENCOUNTERS, "", False, False)

    # removals
    DEPARTED_DATE = ("Departed Date", Tables.REMOVALS, "", False, False)
    PORT_OF_DEPARTURE = ("Port of Departure", Tables.REMOVALS, "", False, False)
    DEPARTURE_COUNTRY = ("Departure Country", Tables.REMOVALS, "", False, False)
    DOCKET_AOR = ("Docket AOR", Tables.REMOVALS, "", False, False)
    APPREHENSION_STATE = ("Apprehension State", Tables.REMOVALS, "", False, False)
    APPREHENSION_COUNTY = ("Apprehension County", Tables.REMOVALS, "", False, False)
    CASE_STATUS = ("Case Status", Tables.REMOVALS, "", False, False)
    GENDER = ("Gender", Tables.REMOVALS, "", False, False)
    BIRTH_COUNTRY = ("Birth Country", Tables.REMOVALS, "", False, False)
    CITIZENSHIP_COUNTRY = ("Citizenship Country", Tables.REMOVALS, "", False, False)
    BIRTH_DATE = ("Birth Date", Tables.REMOVALS, "", True, False)
    BIRTH_YEAR = ("Birth Year", Tables.REMOVALS, "", False, False)
    ENTRY_DATE = ("Entry Date", Tables.REMOVALS, "", False, False)
    ENTRY_STATUS = ("Entry Status", Tables.REMOVALS, "", False, False)
    MSC_NCIC_CHARGE = ("MSC NCIC Charge", Tables.REMOVALS, "", False, False)
    MSC_NCIC_CHARGE_CODE = ("MSC NCIC Charge Code", Tables.REMOVALS, "", True, False)
    MSC_CHARGE_DATE = ("MSC Charge Date", Tables.REMOVALS, "", False, False)
    MSC_CRIMINAL_CHARGE_STATUS = ("MSC Criminal Charge Status", Tables.REMOVALS, "", False, False)
    MSC_CRIMINAL_CHARGE_STATUS_CODE = ("MSC Criminal Charge Status Code", Tables.REMOVALS, "", True, False)
    MSC_CONVICTION_DATE = ("MSC Conviction Date", Tables.REMOVALS, "", False, False)
    CASE_THREAT_LEVEL = ("Case Threat Level", Tables.REMOVALS, "", False, False)
    CASE_CRIMINALITY = ("Case Criminality", Tables.REMOVALS, "", False, False)
    FELON = ("Felon", Tables.REMOVALS, "", False, False)
    PROCESSING_DISPOSITION = ("Processing Disposition", Tables.REMOVALS, "", False, False)
    CASE_CATEGORY = ("Case Category", Tables.REMOVALS, "", False, False)
    FINAL_PROGRAM = ("Final Program", Tables.REMOVALS, "", False, False)
    FINAL_PROGRAM_CODE = ("Final Program Code", Tables.REMOVALS, "", True, False)
    CASE_CATEGORY_TIME_OF_ARREST = ("Case Category Time of Arrest", Tables.REMOVALS, "", True, False)
    LATEST_ARREST_PROGRAM_CURRENT = ("Latest Arrest Program Current", Tables.REMOVALS, "", False, False)
    LATEST_ARREST_PROGRAM_CURRENT_CODE = ("Latest Arrest Program Current Code", Tables.REMOVALS, "", True, False)
    LATEST_PERSON_APPREHENSION_DATE = ("Latest Person Apprehension Date", Tables.REMOVALS, "", False, False)
    FINAL_ORDER_YES_NO = ("Final Order Yes No", Tables.REMOVALS, "", False, False)
    FINAL_ORDER_DATE = ("Final Order Date", Tables.REMOVALS, "", False, False)
    FINAL_CHARGE_CODE = ("Final Charge Code", Tables.REMOVALS, "", True, False)
    FINAL_CHARGE_SECTION_CODE = ("Final Charge Section Code", Tables.REMOVALS, "", True, False)
    PRIOR_DEPORT_YES_NO = ("Prior Deport Yes No", Tables.REMOVALS, "", False, False)
    LATEST_PERSON_DEPARTED_DATE = ("Latest Person Departed Date", Tables.REMOVALS, "", False, False)
    ALIEN_FILE_NUMBER = ("Alien File Number", Tables.REMOVALS, "", True, False)
    EID_CASE_ID = ("EID Case ID", Tables.REMOVALS, "", True, False)
    EID_SUBJECT_ID = ("EID Subject ID", Tables.REMOVALS, "", True, False)
    UNIQUE_IDENTIFIER = ("Unique Identifier", Tables.REMOVALS, "derived from alien registration number", False, False)
    # arrests
    APPREHENSION_DATE = ("Apprehension Date", Tables.ARRESTS, "", False, False)
    APPREHENSION_STATE = ("Apprehension State", Tables.ARRESTS, "", False, False)
    APPREHENSION_COUNTY = ("Apprehension County", Tables.ARRESTS, "", False, False)
    APPREHENSION_AOR = ("Apprehension AOR", Tables.ARRESTS, "", False, False)
    FINAL_PROGRAM = ("Final Program", Tables.ARRESTS, "", False, False)
    FINAL_PROGRAM_GROUP = ("Final Program Group", Tables.ARRESTS, "", False, True)
    APPREHENSION_METHOD = ("Apprehension Method", Tables.ARRESTS, "", False, False)
    APPREHENSION_CRIMINALITY = ("Apprehension Criminality", Tables.ARRESTS, "", False, False)
    CASE_STATUS = ("Case Status", Tables.ARRESTS, "", False, False)
    CASE_CATEGORY = ("Case Category", Tables.ARRESTS, "", False, False)
    DEPARTED_DATE = ("Departed Date", Tables.ARRESTS, "", False, False)
    DEPARTURE_COUNTRY = ("Departure Country", Tables.ARRESTS, "", False, False)
    FINAL_ORDER_YES_NO = ("Final Order Yes No", Tables.ARRESTS, "YES/NO depending on whether final order date is defined", False, True)
    FINAL_ORDER_DATE = ("Final Order Date", Tables.ARRESTS, "date of removal order or a non-appealed order", False, False)
    BIRTH_DATE = ("Birth Date", Tables.ARRESTS, "", True, False)
    BIRTH_YEAR = ("Birth Year", Tables.ARRESTS, "", False, False)
    CITIZENSHIP_COUNTRY = ("Citizenship Country", Tables.ARRESTS, "", False, False)
    GENDER = ("Gender", Tables.ARRESTS, "", False, False)
    APPREHENSION_SITE_LANDMARK = ("Apprehension Site Landmark", Tables.ARRESTS, "", False, False)
    ALIEN_FILE_NUMBER = ("Alien File Number", Tables.ARRESTS, "", True, False)
    EID_CASE_ID = ("EID Case ID", Tables.ARRESTS, "", True, False)
    EID_SUBJECT_ID = ("EID Subject ID", Tables.ARRESTS, "", True, False)
    UNIQUE_IDENTIFIER = ("Unique Identifier", Tables.ARRESTS, "derived from alien registration number", False, False)
    # detentions
    STAY_BOOK_IN_DATE_TIME = ("Stay Book In Date Time", Tables.DETENTIONS, "", False, False)
    BOOK_IN_DATE_TIME = ("Book In Date Time", Tables.DETENTIONS, "", False, False)
    DETENTION_FACILITY = ("Detention Facility", Tables.DETENTIONS, "redundant with detention facility code", False, True)
    DETENTION_FACILITY_CODE = ("Detention Facility Code", Tables.DETENTIONS, "", False, False)
    DETENTION_BOOK_OUT_DATE_TIME = ("Detention Book Out Date Time", Tables.DETENTIONS, "", False, False)
    STAY_BOOK_OUT_DATE_TIME = ("Stay Book Out Date Time", Tables.DETENTIONS, "", False, False)
    DETENTION_RELEASE_REASON = ("Detention Release Reason", Tables.DETENTIONS, "", False, False)
    STAY_BOOK_OUT_DATE = ("Stay Book Out Date", Tables.DETENTIONS, "", False, False)
    STAY_RELEASE_REASON = ("Stay Release Reason", Tables.DETENTIONS, "", False, False)
    RELIGION = ("Religion", Tables.DETENTIONS, "Inconsistent labels. For example, CATHOLIC, Catholic, CATH", False, True)
    GENDER = ("Gender", Tables.DETENTIONS, "", False, False)
    MARITAL_STATUS = ("Marital Status", Tables.DETENTIONS, "", False, False)
    BIRTH_DATE = ("Birth Date", Tables.DETENTIONS, "", True, False)
    BIRTH_YEAR = ("Birth Year", Tables.DETENTIONS, "", False, False)
    ETHNICITY = ("Ethnicity", Tables.DETENTIONS, "Hispanic or not hispanic", False, False)
    ENTRY_STATUS = ("Entry Status", Tables.DETENTIONS, "Needs to be normalized, but probably usable", False, False)
    FELON = ("Felon", Tables.DETENTIONS, "", False, False)
    BOND_POSTED_DATE = ("Bond Posted Date", Tables.DETENTIONS, "", False, False)
    BOND_POSTED_AMOUNT = ("Bond Posted Amount", Tables.DETENTIONS, "", False, False)
    CASE_STATUS = ("Case Status", Tables.DETENTIONS, "", False, False)
    CASE_CATEGORY = ("Case Category", Tables.DETENTIONS, "", False, False)
    FINAL_ORDER_YES_NO = ("Final Order Yes No", Tables.DETENTIONS, "", False, False)
    FINAL_ORDER_DATE = ("Final Order Date", Tables.DETENTIONS, "", False, False)
    CASE_THREAT_LEVEL = ("Case Threat Level", Tables.DETENTIONS, "", False, False)
    BOOK_IN_CRIMINALITY = ("Book In Criminality", Tables.DETENTIONS, "", False, False)
    FINAL_CHARGE = ("Final Charge", Tables.DETENTIONS, "", False, False)
    DEPARTED_DATE = ("Departed Date", Tables.DETENTIONS, "", False, False)
    DEPARTURE_COUNTRY = ("Departure Country", Tables.DETENTIONS, "", False, False)
    INITIAL_BOND_SET_AMOUNT = ("Initial Bond Set Amount", Tables.DETENTIONS, "", False, False)
    CITIZENSHIP_COUNTRY = ("Citizenship Country", Tables.DETENTIONS, "", False, False)
    FINAL_PROGRAM = ("Final Program", Tables.DETENTIONS, "", False, False)
    MOST_SERIOUS_CONVICTION_MSC_CHARGE_CODE = ("Most Serious Conviction (MSC) Charge Code", Tables.DETENTIONS, "redundant", False, True)
    MSC_CHARGE = ("MSC Charge", Tables.DETENTIONS, "", False, False)
    ALIEN_FILE_NUMBER = ("Alien File Number", Tables.DETENTIONS, "", True, False)
    EID_CASE_ID = ("EID Case ID", Tables.DETENTIONS, "", True, False)
    EID_SUBJECT_ID = ("EID Subject ID", Tables.DETENTIONS, "", True, False)
    UNIQUE_IDENTIFIER = ("Unique Identifier", Tables.DETENTIONS, "derived from alien registration number", False, False)
    
    def __init__(self, column_name, table, description, redacted, bad_data):
        self.column_name = column_name
        self.table = table
        self.description = description
        self.redacted = redacted
        self.bad_data = bad_data
        self.useable = not redacted and not bad_data

if __name__ == "__main__":
    depared_date_column = Columns.DEPARTED_DATE
    print(f"column name: {depared_date_column.column_name}")
    print(f"table: {depared_date_column.table}")
    print(f"useable: {depared_date_column.useable}")
